// <auto-generated />
namespace SquidsMovieApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieDbCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieDbCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151458486_MovieDbCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
